version: 2

jobs:
  checkout:
    docker:
      - image: node:8.6.0
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - ./*
  scala:
    docker:
      - image: openjdk:8
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install SBT
          command: |
            curl -L -o sbt.deb http://dl.bintray.com/sbt/debian/sbt-1.0.4.deb
            dpkg -i sbt.deb
            rm sbt.deb
            apt-get update
            apt-get install sbt
      - run:
          name: Download Scala dependencies
          working_directory: backend/
          command: sbt update
      - run:
          name: Run Scala tests
          working_directory: backend/
          command: sbt test

  deploy:
    docker:
      - image: node:8.6.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy
          command: bash .circleci/deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - scala:
          requires:
            - checkout
      - deploy:
          requires:
            - scala